### ISSUE TITLE
Add support for conditionals

### ISSUE THREAD

**Issue by DevAndrewGeorge** [DevAndrewGeorge/config-generator#1]
Conditionals would allow for templates and outputs to be processed only if the conditionals pass.

An example:
```yaml
variables:
  greeting:
    static: hello world
templates:
  conditional-template-1:
    when: greeting == "hello world"
    inline: "{{ greeting }} and goodbye moon"
  conditional-template-2:
    when: greeting == "goodbye moon"
    inline: "hello world and {{ greeting }}"
```
