### ISSUE TITLE
Add support for transformers

### ISSUE THREAD

**Issue by DevAndrewGeorge** [DevAndrewGeorge/config-generator#2]
Currently the spec only generates entirely new templates. A transformer would take some form of a template as input, match parts of it, and perform some transformation function (replace, delete, append, etc.) on the template.

It'll be curious to see how these would interact with nested templates.

Example:
```yaml
templates:
  transformer-template-1:
    transform:
      # file: <<path to template>>
      # template: <<name of template>>
      inline: "HELLO={{ world_variable }}"
      apply:
      - match: HELLO=(.*)
        replace: HELLO="(\1)"
      - match: .*
        upper:
      - append: GOODBYE="{{ moon_variable }}"
```
