### ISSUE TITLE
Expose templates as variables

### ISSUE THREAD

**Issue by DevAndrewGeorge** [DevAndrewGeorge/config-generator#3]
Very useful in respecting the DRY principle of programming.
Example:
```yaml
templates:
  template-1: hello {{ world_variable }}
  tempalte-2: "{{ templates.template-1 }}, goodbye moon"
```
