### ISSUE TITLE
Implement an include directive

### ISSUE THREAD

**Issue by DevAndrewGeorge** [DevAndrewGeorge/config-generator#4]
This would allow for compositions of configuration files via merging. This would be useful in multi-environment scenarios. Perhaps you have an organization-wide `main.yaml` file, but you have separate `production-variables.yaml` and `stage-variables.yaml` files for each environment.

```yaml
# main.yaml
plugins:
variables:
templates:
outputs:
include:
- production-variables.yaml
```
